# Generated by Django 6.0.4 on 2026-04-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_user_account_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_account_name',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='notes',
            field=models.TextField(blank=True, help_text='Instructions for the user', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txd_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
