# Generated by Django 6.0.4 on 2026-05-05 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_date_joined_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_stamp',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
