# Generated by Django 6.0.4 on 2026-04-19 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_lifetime_deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_machines', models.IntegerField(default=900)),
                ('floors', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='GJP_Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_seed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hot_trigger', models.DecimalField(decimal_places=2, max_digits=12)),
                ('must_hit_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contribution_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('island', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gjp_pool', to='game.island')),
            ],
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('win_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('symbols_matrix', models.JSONField()),
                ('is_gjp_win', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('island', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.island')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
