# Generated by Django 6.0.4 on 2026-04-19 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('machine_number', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['floor', 'machine_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='spinhistory',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='spinhistory',
            name='game_spinhi_user_id_dd0b7d_idx',
        ),
        migrations.AddField(
            model_name='machine',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='island',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='game.island'),
        ),
        migrations.AddField(
            model_name='spinhistory',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.machine'),
        ),
        migrations.RemoveField(
            model_name='spinhistory',
            name='island',
        ),
        migrations.AlterUniqueTogether(
            name='machine',
            unique_together={('island', 'floor', 'machine_number')},
        ),
    ]
