# Generated by Django 6.0.4 on 2026-04-21 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_machine_alter_spinhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spinhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='spinhistory',
            name='machine',
        ),
        migrations.AddField(
            model_name='spinhistory',
            name='island',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.island'),
        ),
        migrations.AddField(
            model_name='spinhistory',
            name='lines_won',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='spinhistory',
            index=models.Index(fields=['user', '-timestamp'], name='game_spinhi_user_id_dd0b7d_idx'),
        ),
    ]
