# Generated by Django 6.0.4 on 2026-04-21 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_spinhistory_options_remove_spinhistory_machine_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='spinhistory',
            name='game_spinhi_user_id_dd0b7d_idx',
        ),
        migrations.AddField(
            model_name='spinhistory',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.machine'),
        ),
    ]
