# Generated by Django 6.0.4 on 2026-04-30 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_spinhistory_game_spinhi_user_id_dd0b7d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_spins_remaining', models.IntegerField(default=0)),
                ('locked_bet_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.island')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'island')},
            },
        ),
    ]
