# Generated by Django 6.0.4 on 2026-04-30 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_playergamestate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinhistory',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.machine'),
        ),
        migrations.AddIndex(
            model_name='spinhistory',
            index=models.Index(fields=['user', '-timestamp'], name='game_spinhi_user_id_dd0b7d_idx'),
        ),
    ]
