# Generated by Django 6.0.4 on 2026-05-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_spinhistory_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
